# action.yml
name: 'Virtual Dev Environments'
description: 'Create virtual dev environments from branch'
inputs:
  action:
    description: 'action to perfrom: create, delete, deploy'
    required: true
    default: ''
  branch:
    description: 'branch used as namespace in k8s'
    required: true
    default: ''
  aws_access_key_id:
    description: 'aws access key id'
    required: true
    default: ''
  aws_secret_access_key:
    description: 'aws secret access key'
    required: true
    default: ''
  vault_password:
    description: 'password use for ansible vault'
    required: false
    default: ''
  service_name:
    description: 'name of service to deploy'
    required: false
    default: ''
  version:
    description: 'version of service to deploy'
    required: false
    default: 'latest'

runs:
  using: 'docker'
  image: 'chromeriver/virtual-env:latest'
  args:
    - ${{ inputs.branch }}
    - ${{ inputs.aws_access_key_id }}
    - ${{ inputs.service_name }}
    - ${{ inputs.vault_password }}
    - ${{ inputs.service_name }}
    - ${{ inputs.version }}
