apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-props
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  "{{ .Values.app_name }}.properties": |-
    {{ .Files.Get "files/microservice.properties" | b64enc }}
